### ISSUE TITLE
1.2 and 1.3 fail to build due to lintVitalRelease errors

### ISSUE THREAD

**Issue by relan** [subchannel13/EnchantedFortress#17] opened 2017-07-15 13:53 UTC
Steps to reproduce: run `gradle assembleRelease`. Logs:

https://f-droid.org/wiki/page/hr.kravarscan.enchantedfortress/lastbuild_3  
https://f-droid.org/wiki/page/hr.kravarscan.enchantedfortress/lastbuild_4

Linter also suggests how to fix this.

**Comment by subchannel13** [comment] 2017-07-15 14:10
I saw that error in v1.2 and for v1.3 I changed project's lint rules thinking they would apply. Here are problems with solving this:
* I can't guarantee proper fix (full translation) in timely manner since that depends on other contributors and French translator confirmed he/she didn't translate certain part (which happens to be the biggest text) at the time of contribution.
* `translatable=false` as suggested by lint in my Android Studio is no go, first of it's a balant lie, those entries should and some are translated and secondly it would cause another error.
* Turning lint off is something I'd rather not do.

Is there a way to modify build script to include custom lint rules? My vision of proper fix for this one would be to lower error severity to warning. To be honest it's questionable why this is an error because Andriod has well defined behavior in this case, it falls back to "default" language.

**Comment by relan** [comment] 2017-07-15 14:48
> Is there a way to modify build script to include custom lint rules? My vision of proper fix for this one would be to lower error severity to warning.

You can disable this particular warning: https://stackoverflow.com/questions/27472282/how-to-sign-apk-on-android-studio-even-with-non-translated-strings#31841490

**Comment by subchannel13** [comment] 2017-07-15 16:23
Oh, nice! Will give it a shot.

**Comment by subchannel13** [comment] 2017-07-15 18:08
Package sent, now we wait.

**Comment by subchannel13** [comment] 2017-07-20 15:32
v1.4 builds successfully.

**Closed by subchannel13** 2017-07-20 15:32 UTC
