### ISSUE TITLE
Demon turn counter not shown if above 1000

### ISSUE THREAD

**Issue by emilhem** [subchannel13/EnchantedFortress#10] opened 2017-06-06 20:39 UTC
I'm using LineageOS (basically Android) 7.1.2 on a One Plus X (onyx) and when the demon counter is above 1000 it doesn't display the number of turns. This was confusing for me since I thought that I would win if I selected that option.

**Comment by subchannel13** [comment] 2017-06-07 07:29
Oh, built it yourself :)? Can you provide screenshot of the problem?

**Comment by mueller-ma** [comment] 2017-07-20 19:59
Can confirm population not going over 100000.
Lineageos on oneplusx. Android 7.1.2

**Comment by subchannel13** [comment] 2017-07-23 18:28
@mueller-ma That's by design, population and walls are limited to 100000. What emilhem describes doesn't relate to that limit.

**Comment by subchannel13** [comment] 2017-08-28 19:03
Is this still happening? I have neither a device or OS as issue reporter and on my devices the issue doesn't happen. Can screenshot be provided?

**Comment by subchannel13** [comment] 2017-09-14 18:56
Closing, unfortunately. I cannot reproduce and submitter is not responding to requests for more information.

**Closed by subchannel13** 2017-09-14 18:56 UTC
